### ISSUE TITLE
SPL/ZFS 0.7.3 is released. PKGBUILD bump?

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-extra#139]
I've build 0.7.3 for my own machine and the extramodules and utils build without issue.

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.3

**Comment by philmmanjaro** [comment]
I noticed it a while ago. Since today some Kernels got released I might update zfs also.

**Comment by jonathonf** [comment]
It also looks like 0.7.3 will work for kernel 4.15 (at least, it compiles).

I can upload my builds to `unstable` if you want?

**Comment by philmmanjaro** [comment]
Would be nice if you may update it also for Manjaro-64. I've pushed some new kernels, so you may need to rebuild those extramodules once more before uploading them.

**Comment by jonathonf** [comment]
OK, can do. I'll do a rebuild for the latest kernel round.

Looks like 0.7.3 _isn't_ actually working with kernel 4.15:

```
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c: In function 'taskq_dispatch':
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c:593:16: error: 'struct timer_list' has no member named 'data'
  t->tqent_timer.data = 0;
                ^
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c: In function 'taskq_dispatch_delay':
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c:643:16: error: 'struct timer_list' has no member named 'data'
  t->tqent_timer.data = (unsigned long)t;
                ^
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c:644:26: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  t->tqent_timer.function = task_expire;
                          ^
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c: In function 'taskq_init_ent':
/build/src/spl-spl-0.7.3/module/spl/spl-taskq.c:735:2: error: implicit declaration of function 'init_timer'; did you mean 'init_timers'? [-Werror=implicit-function-declaration]
  init_timer(&t->tqent_timer);
  ^~~~~~~~~~
  init_timers
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:310: /build/src/spl-spl-0.7.3/module/spl/spl-taskq.o] Error 1
```

Let's see what's on the ZoL issue tracker...

**Comment by philmmanjaro** [comment]
The timer had changed. I had to update the Nvidia patches also ...

**Comment by philmmanjaro** [comment]
@jonathonf: do we need a rebuild every kernel update for these modules?

**Comment by jonathonf** [comment]
I think so - previous module compilations fail on newer kernel versions.
